/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nike.run.club;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
/**
 *
 * @author canertasan
 */
public class FirstInterface extends javax.swing.JFrame { 

    /**
     * Creates new form NewJFrame
     */
    public FirstInterface() {
        super("Nike+Run Club");
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        setIcon();
        Toolkit tk=Toolkit.getDefaultToolkit();
            int xsize= (int) tk.getScreenSize().getWidth();
            int ysize= (int) tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        PathButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                PathInterface pi=new PathInterface();
//                pi.setVisible(true);
                Data.pi.setVisible(true);
                hide();
            }
        });
        
        nrcButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               SecondInterface si = new SecondInterface(); 
               si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
               si.setVisible(true);
               si.setResizable(false); 
               si.setExtendedState(JFrame.MAXIMIZED_BOTH); 
            }
        });
           
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nrcButton = new javax.swing.JButton();
        PathButton = new javax.swing.JButton();
        BackGround = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nrcButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/Interface_01_NRC.png"))); // NOI18N
        nrcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrcButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nrcButton);
        nrcButton.setBounds(630, 220, 650, 690);

        PathButton.setBackground(new java.awt.Color(0, 0, 0));
        PathButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/Background_NrcFF.png"))); // NOI18N
        getContentPane().add(PathButton);
        PathButton.setBounds(1880, 0, 90, 110);

        BackGround.setForeground(new java.awt.Color(255, 255, 255));
        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/Background_NrcFF.png"))); // NOI18N
        BackGround.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackGround.setPreferredSize(new java.awt.Dimension(2000, 1000));
        BackGround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackGroundActionPerformed(evt);
            }
        });
        getContentPane().add(BackGround);
        BackGround.setBounds(-310, 0, 2290, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackGroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackGroundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackGroundActionPerformed

    private void nrcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrcButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrcButtonActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackGround;
    private javax.swing.JButton PathButton;
    private javax.swing.JButton nrcButton;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo_NRC.png")));
    }
}
