/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nike.run.club;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import java.util.TimerTask;
import java.util.Timer;

/**
 *
 * @author canertasan
 */
public class SecondInterface extends javax.swing.JFrame {

    int secondPassed = 1;
    String winner;
    int luckyNumber;  
    public SecondInterface() {
        super("Nike+Run Club");
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        setIcon();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        num5.setVisible(false);
        num4.setVisible(false);
        num3.setVisible(false);
        num2.setVisible(false);
        num1.setVisible(false);
        Konfeti.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        Timer timer = new Timer();
        Random rnd = new Random();
//        PersonArrayList pal = new PersonArrayList();
//        luckyNumber = rnd.nextInt(pal.PersonData.size());
//        winner = pal.PersonData.get(luckyNumber).getInstaName();
//        System.out.println(pal.PersonData.size());

        Data.UpdatePersonList();
        luckyNumber = rnd.nextInt(Data.PersonData.size());
        winner = Data.PersonData.get(luckyNumber).getInstaName();
        System.out.println(Data.PersonData.size());
        
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                secondPassed++;
                if (secondPassed == 2) {
                    num5.setVisible(false);
                    num4.setVisible(true);
                    jLabel4.setVisible(true);
                } else if (secondPassed == 3) {
                    jLabel4.setVisible(false);
                    num4.setVisible(false);
                    num3.setVisible(true);
                    jLabel3.setVisible(true);
                } else if (secondPassed == 4) {
                    jLabel3.setVisible(false);
                    num3.setVisible(false);
                    num2.setVisible(true);
                    jLabel2.setVisible(true);
                } else if (secondPassed == 5) {
                    jLabel2.setVisible(false);
                    num2.setVisible(false);
                    num1.setVisible(true);
                    jLabel5.setVisible(true);
                } else if(secondPassed == 6){
                    jLabel5.setVisible(false);
                    num1.setVisible(false);
                    Winner.setText(winner);
                    Konfeti.setVisible(true);
                    timer.cancel();//stop
                }
            }
        };
              
        for(int i=0; i<Data.PersonData.size();i++){
            System.out.println(Data.PersonData.get(i).getInstaName());
        }

        go.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                go.setVisible(false);
                num5.setVisible(true);
                timer.scheduleAtFixedRate(task, 1000, 1000);//Start
            }
        });
        setSize(1920, 1080);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Konfeti = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        go = new javax.swing.JButton();
        Winner = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Konfeti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/KonfetiGif.gif"))); // NOI18N
        getContentPane().add(Konfeti, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 710, 480, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/mo.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 380, 440, 280));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/mo.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 150, 410, 260));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/mo.gif"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 700, 410, 250));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/mo.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 700, 420, 240));

        num1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/Number_01F_NRC.png"))); // NOI18N
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 740, 210, 200));

        num2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/Number_02F_NRC.png"))); // NOI18N
        getContentPane().add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 740, 210, 200));

        num5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/Number_05F_NRC.png"))); // NOI18N
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        getContentPane().add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 740, 210, 200));

        num4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/Number_04F_NRC.png"))); // NOI18N
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        getContentPane().add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 740, 210, 200));

        num3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/Number_03F_NRC.png"))); // NOI18N
        getContentPane().add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 740, 210, 200));

        go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/Number_GoF_NRC.png"))); // NOI18N
        getContentPane().add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 740, 210, 200));

        Winner.setFont(new java.awt.Font("Trade Gothic for Nike 365 BdCn", 1, 60)); // NOI18N
        Winner.setForeground(new java.awt.Color(240, 240, 240));
        Winner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Winner.setToolTipText("");
        Winner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Winner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Winner, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 800, 510, 80));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike/run/club/Background_Nrc2.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num5ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num4ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(Person args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Konfeti;
    private javax.swing.JLabel Winner;
    private javax.swing.JButton go;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo_NRC.png")));
    }
}
